2024-02-28 15:36:27,276 ERROR: Exception on /index [GET] [in C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_login\login_manager.py", line 180, in unauthorized
    if self.login_message:
       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\speaklater.py", line 24, in __len__
    return len(str(self))
               ^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\speaklater.py", line 21, in __str__
    return str(self._func(*self._args, **self._kwargs))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\__init__.py", line 756, in gettext
    return get_domain().gettext(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\__init__.py", line 648, in gettext
    t = self.get_translations()
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\__init__.py", line 609, in get_translations
    locale = get_locale()
             ^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\__init__.py", line 263, in get_locale
    rv = babel.locale_selector()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\app\__init__.py", line 15, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
                                               ~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'LANGUAGES'
2024-02-28 15:37:07,108 ERROR: Exception on /index [GET] [in C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_login\login_manager.py", line 180, in unauthorized
    if self.login_message:
       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\speaklater.py", line 24, in __len__
    return len(str(self))
               ^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\speaklater.py", line 21, in __str__
    return str(self._func(*self._args, **self._kwargs))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\__init__.py", line 756, in gettext
    return get_domain().gettext(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\__init__.py", line 648, in gettext
    t = self.get_translations()
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\__init__.py", line 609, in get_translations
    locale = get_locale()
             ^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\__init__.py", line 263, in get_locale
    rv = babel.locale_selector()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\app\__init__.py", line 15, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
                                               ~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'LANGUAGES'
2024-02-28 15:48:04,893 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-28 18:24:12,524 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-29 18:26:31,308 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-29 20:50:01,894 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-29 20:52:37,199 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-29 20:54:22,113 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-29 21:00:20,686 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-29 21:00:45,358 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-29 21:01:08,229 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-29 21:04:44,036 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-29 21:05:53,561 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-29 21:06:28,285 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-29 21:08:52,267 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-29 21:22:02,331 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-02-29 22:01:57,938 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-03-01 09:26:56,366 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-03-01 09:50:25,006 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-03-01 09:51:09,457 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-03-01 09:53:03,243 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-03-01 09:57:59,768 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-03-01 09:58:44,069 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-03-02 10:57:29,391 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-03-02 11:03:39,490 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-03-02 11:05:30,919 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-03-02 11:06:33,134 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:47]
2024-03-02 11:07:07,428 ERROR: Exception on / [GET] [in C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py", line 868, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask\app.py", line 1243, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\app\routes.py", line 22, in before_request
    g.locale = str(get_locale())
                   ^^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\__init__.py", line 259, in get_locale
    babel = get_babel()
            ^^^^^^^^^^^
  File "C:\Users\nimlord\Desktop\microblogh\venv\Lib\site-packages\flask_babel\__init__.py", line 46, in get_babel
    return app.extensions['babel']
           ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'babel'
2024-03-02 17:06:23,587 INFO: Microblog startup [in C:\Users\nimlord\Desktop\microblogh\app\__init__.py:55]
